# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

dist: bionic

language: generic

before_install:
  - echo $JAVA_HOME
  - which java
  - sudo rm -rf /usr/local/lib/jvm/
  - sudo apt-get install -y openjdk-11-jdk-headless
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
  - which java
  - java -version
  - $JAVA_HOME/bin/java -version

cache:
  directories:
    - $HOME/.m2


jobs:
  include:
    - stage: compile
      script: ./mvnw -q -Dmaven.test.skip=true package
    - stage: run test in parallel
      script: cd backends-common && ../mvnw --no-transfer-progress test
    - script: cd mailbox/cassandra &&../../mvnw --no-transfer-progress test
    - script: ./test_batch1.sh
    - script: cd mailet && ../mvnw --no-transfer-progress test
    - script: cd mdn && ../mvnw --no-transfer-progress test
    - script: cd metrics && ../mvnw --no-transfer-progress test
    - script: cd protocols && ../mvnw --no-transfer-progress test
    - script: cd testing/base && ../../mvnw --no-transfer-progress test

    - script: cd mailbox/api &&../../mvnw --no-transfer-progress test
    - script: cd mailbox/backup &&../../mvnw --no-transfer-progress test
    - script: cd mailbox/elasticsearch &&../../mvnw --no-transfer-progress test
    - script: cd mailbox/event/event-cassandra && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/event/event-memory && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/event/event-rabbitmq && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/event/json && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/lucene &&../../mvnw --no-transfer-progress test
    - script: cd mailbox/maildir &&../../mvnw --no-transfer-progress test
    - script: cd mailbox/memory &&../../mvnw --no-transfer-progress test
    - script: cd mailbox/plugin/quota-mailing && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/plugin/quota-search && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/scanning-search &&../../mvnw --no-transfer-progress test
    - script: cd mailbox/store &&../../mvnw --no-transfer-progress test
    - script: cd mailbox/tika &&../../mvnw --no-transfer-progress test
    - script: cd mailbox/tools/copier && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/tools/indexer && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/tools/jpa-migrator && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/tools/quota-recompute && ../../../mvnw --no-transfer-progress test
    - script: cd server && ../mvnw --no-transfer-progress test
    - script: cd mpt && ../mvnw --no-transfer-progress test
    - script: cd third-party && ../mvnw --no-transfer-progress test
    - script: cd mailbox/jpa &&../../mvnw --no-transfer-progress test
    - script: cd mailbox/plugin/deleted-messages-vault && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/plugin/deleted-messages-vault-cassandra && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/plugin/quota-mailing-cassandra && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/plugin/quota-mailing-memory && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/plugin/quota-search-elasticsearch && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/plugin/quota-search-scanning && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/plugin/spamassassin && ../../../mvnw --no-transfer-progress test
    - script: cd mailbox/spring &&../../mvnw --no-transfer-progress test





