# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

dist: bionic

language: generic

services:
  - docker

before_install:
  - echo $JAVA_HOME
  - which java
  - sudo rm -rf /usr/local/lib/jvm/
  - sudo apt-get install -y openjdk-11-jdk-headless
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
  - which java
  - java -version
  - $JAVA_HOME/bin/java -version

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: compile and install dependencies into $HOME/.m2
      script: .travis/compile_and_install.sh
      name: compile_and_install.sh

    - stage: run test in parallel (starting with ones that run the longest)
      # Comment in if we don't want to run tests for pull requests
      # if: type != pull_request
      script: .travis/server_protocols.sh
      name: server_protocols.sh
    - script: .travis/server_protocols2.sh
      name: server_protocols2.sh (only if not PR)
    - script: .travis/server_container.sh
      name: server_container.sh
    - script: .travis/server_protocols3.sh
      name: server_protocols3.sh
    - script: .travis/mailbox_mailet_examples.sh
      name: mailbox_mailet_examples.sh
    - script: .travis/server_protocols4.sh
      name: server_protocols4.sh
    - script: .travis/mpt.sh
      name: mpt.sh
    - script: .travis/server_blob.sh
      name: server_blob.sh
    - script: .travis/server_app_dns-service_mailrepository_task.sh
      name: server_app_dns-service_mailrepository_task.sh
    - script: .travis/misc.sh
      name: misc.sh
    - script: .travis/json_backends-common.sh
      name: json_backends-common.sh
    - script: .travis/server_data.sh
      name: server_data.sh
    - script: .travis/server_mailet_testing.sh
      name: server_mailet_testing.sh
    - script: .travis/server_queue.sh
      name: server_queue.sh


