# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

dist: bionic

language: generic

services:
  - docker

before_install:
  - echo $JAVA_HOME
  - which java
  - sudo rm -rf /usr/local/lib/jvm/
  - sudo apt-get install -y openjdk-11-jdk-headless
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
  - which java
  - java -version
  - $JAVA_HOME/bin/java -version

cache:
  directories:
    - $HOME/.m2


jobs:
  include:
    - stage: compile and install dependencies into $HOME/.m2 folder
      script: ./travis_phase1.sh

    - stage: run test in parallel (starting with ones that run the longest)
      script: ./travis_phase2_job_mailbox_mailet.sh
    - script: ./travis_phase2_job_server_app.sh
    - script: ./travis_phase2_job_server_blob.sh
    - script: ./travis_phase2_job_server_container.sh
    - script: ./travis_phase2_job_server_data.sh
    - script: ./travis_phase2_job_server_dns-service.sh
    - script: ./travis_phase2_job_server_mailet.sh
    - script: ./travis_phase2_job_server_mailrepository.sh
    - script: ./travis_phase2_job_server_protocols.sh
    - script: ./travis_phase2_job_server_protocols2.sh
    - script: ./travis_phase2_job_server_queue.sh
    - script: ./travis_phase2_job_server_task.sh
    - script: ./travis_phase2_job_server_testing.sh

    - script: cd mpt && ../mvnw -T 1C  --no-transfer-progress test
    - script: cd backends-common && ../mvnw -T 1C  --no-transfer-progress test
    - script: cd core && ../mvnw -T 1C  --no-transfer-progress test
    - script: cd event-sourcing && ../mvnw -T 1C  --no-transfer-progress test
    - script: cd examples && ../mvnw -T 1C  --no-transfer-progress test
    - script: cd javax-mail-extension && ../mvnw -T 1C  --no-transfer-progress test

    - script: cd mdn && ../mvnw -T 1C  --no-transfer-progress test
    - script: cd metrics && ../mvnw -T 1C  --no-transfer-progress test
    - script: cd protocols && ../mvnw -T 1C  --no-transfer-progress test
    - script: cd testing/base && ../../mvnw -T 1C  --no-transfer-progress test
    - script: cd third-party && ../mvnw -T 1C  --no-transfer-progress test






